import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provieder";
import { TypeContextWrapper } from "@/typeContext";
import { MovieContextWrapper } from "@/watchContext";
import { SearchAnimeContextWrapper } from "@/searchAnimeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" overflow-y-scroll bg-black text-white font-bold font-sans m-0 p-0  overflow-x-hidden ">
        <div className="container ">
          <Providers>
            <TypeContextWrapper>
              <MovieContextWrapper>
                <SearchAnimeContextWrapper>{children}</SearchAnimeContextWrapper>
              </MovieContextWrapper>
            </TypeContextWrapper>
          </Providers>
        </div>
      </body>
    </html>
  );
}
